### ISSUE TITLE
doesn't work on external server (non-localhost)

### ISSUE THREAD

**Issue by Sebush** [w3c/Mobile-Checker#103]
{external-domain}/mobile-alpha/socket.io/?EIO=2&transport=polling&t=1435577302372-0 404 (Not Found)

**Comment by guibbs** [comment]
Hi Sebush,

You will have to make some changes [in the client script](https://github.com/w3c/Mobile-Checker/blob/master/public/js/socket.io.js):

```
if(window.location.host == "localhost:3000")
    var socket = io.connect();
else
    var socket = io.connect({ path: '/mobile-alpha/socket.io' });
```

replace these lines with:

```
var socket = io.connect();
```

if you still get an error try to specify the location of socket.io on your server:

```
var socket = io.connect({ path: '/{external-domain-path}/socket.io' });
```

Let me know if you are still getting errors!

**Comment by dontcallmedom** [comment]
@guibbs FWIW, I think it is an issue that one has to edit the code to get it to work — ideally, this would be done via some configuration file.

**Comment by guibbs** [comment]
@dontcallmedom I agree. I will add that to the todo list. The configuration file will be needed anyway. @Sebush the solution I gave you is only temporary, like @dontcallmedom said it is definitively something we have to fix.
