### ISSUE TITLE
Can't access my site

### ISSUE THREAD

**Issue by terrybarth** [w3c/Mobile-Checker#125]
Getting this error on these two sites: www.terrybarth.com and www.terrybarthdesign.com

error while resolving http://www.terrybarthdesign.com/work.html. Check the spelling of the host, the protocol (http, https) and ensure that the page is accessible from the public Internet.
Url 

They both come up in a browser.

**Comment by guibbs** [comment]
Thanks for reporting that @terrybarth . I linked your issue there: https://github.com/w3c/insafe/issues/9
Insafe is the API we use to check the dns resolution.

**Comment by tripu** [comment]
Closing this because: a) Mobile-Checker is discontinued; and b) the corresponding issue of Insafe has been closed.
