### ISSUE TITLE
Delete obsolete branches (?)

### ISSUE THREAD

**Issue by tripu** [w3c/Mobile-Checker#131]
ie:
- `astorije/coverage`
- `guibbs/dependencies-update-mobile-web-browser-emulator`
- `exif`
- `guibbs/UI-patch-1`

[github.com/w3c/Mobile-Checker/branches/all](https://github.com/w3c/Mobile-Checker/branches/all)

**Comment by tripu** [comment]
Deleted a few old branches.

**Comment by qwertychouskie** [comment]
@tripu https://github.com/w3c/Mobile-Checker/tree/guibbs/dependencies-update-mobile-web-browser-emulator still needs to be deleted.

**Comment by tripu** [comment]
@qwertychouskie: done, thanks.

GH didn't allow me to remove it, arguing that it was being used in an open PR (?), so I removed it from the command line.
