### ISSUE TITLE
<a class="_42ft _4jy0 _517i _517h _51sy" role="button" rel="dialog" ajaxify="/settings/language/language/?uri=https%3A%2F%2Fpt-br.facebook.com%2Funsupportedbrowser&amp;source=www_list_selector_more" href="#" title="Weitere Sprachen anzeigen"><

### ISSUE THREAD

**Issue by Tommy-Strange-88** [w3c/Mobile-Checker#141]

**Comment by Tommy-Strange-88** [comment]
<p xmlns:dct="http://purl.org/dc/terms/" xmlns:vcard="http://www.w3.org/2001/vcard-rdf/3.0#">
  <a rel="license"
     href="http://creativecommons.org/publicdomain/zero/1.0/">
    <img src="http://i.creativecommons.org/p/zero/1.0/88x31.png" style="border-style: none;" alt="CC0" />
  </a>
  <br />
  To the extent possible under law,
  <a rel="dct:publisher"
     href="https://www.facebook.com/natalie.przybilla.39">
    <span property="dct:title">Natalie Przybilla</span></a>
  has waived all copyright and related or neighboring rights to
  this work.
This work is published from:
<span property="vcard:Country" datatype="dct:ISO3166"
      content="DE" about="https://www.facebook.com/natalie.przybilla.39">
  Deutschland</span>.
</p>

**Comment by qwertychouskie** [comment]
???????? What is this???

**Comment by tripu** [comment]
> *&ldquo;???????? What is this???&rdquo;*

@qwertychouskie, spam. I just reported this account to GH.
